queries:
  exclude:
    - py/import-own-module
    - py/missing-equals
    - py/init-calls-subclass
extraction:
  python:
    python_setup:
      version: 3
    index:
      exclude:
        - .git
        - docs
        - tests
