version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  jobs:
    post_create_environment:
      # Install poetry
      # https://python-poetry.org/docs/#installing-manually
      - pip install poetry==1.6.1
      # Tell poetry to not use a virtual environment
      - poetry config virtualenvs.create false
    post_install:
      # Install dependencies with 'docs' dependency group
      # https://python-poetry.org/docs/managing-dependencies/#dependency-groups
      - poetry install --with docs

python:
  version: 3.8
  install:
    - method: pip
      path: .

sphinx:
  configuration: docs/conf.py
